.github/workflows/BuildDockerOnTag.yml
Dockerfile
docker-compose-build.yml

New tags/releases should now generate a new docker images in Docker Hub.

Docker and Docker-Compose updates

---

gaseous-server/gaseous-server.csproj

Fixes a bug where Visual Studio set some JS files as excluded.

fix: included accidentally excluded scripts

---

gaseous-server/Classes/ImportGames.cs

Zip inspection now works during library scans as well as during import.

fix: expand zip file inspection support

---

README.MD

Update installation documentation to include bare metal installs

---

gaseous-server/Classes/Collections.cs
gaseous-server/Controllers/CollectionsController.cs
gaseous-server/wwwroot/pages/dialogs/collectionaddgame.html
gaseous-server/wwwroot/pages/dialogs/collectionedit.html
gaseous-server/wwwroot/pages/game.html
gaseous-server/wwwroot/styles/style.css
gaseous-tools/Database/MySQL/gaseous-1002.sql

Collections can now have games set to be always included or excluded

---

gaseous-server/ProcessQueue.cs
gaseous-server/Program.cs
gaseous-server/Timer.cs
gaseous-server/wwwroot/pages/settings/system.html

Other processes should now be blocked during database upgrade processes

---

gaseous-server/Classes/ImportGames.cs
gaseous-server/Controllers/RomsController.cs
gaseous-server/ProcessQueue.cs

Recursively import files in the import directory. Duplicates are now moved to the same path, but in the import errors directory.

---

gaseous-server/Controllers/FilterController.cs
gaseous-server/wwwroot/pages/settings/system.html
gaseous-server/wwwroot/scripts/filterformating.js
gaseous-server/wwwroot/styles/style.css

Also adds total image counts to the system info page

Add per platform game counts to the library

---

gaseous-server/Controllers/V1.0/AccountController.cs
gaseous-server/Controllers/V1.1/FirstSetupController.cs
gaseous-server/wwwroot/pages/dialogs/settingsuseredit.html
gaseous-server/wwwroot/pages/dialogs/settingsusernew.html
gaseous-server/wwwroot/pages/dialogs/userprofile.html
gaseous-server/wwwroot/pages/first.html
gaseous-server/wwwroot/pages/login.html

Improved handling of password user feedback

---

gaseous-server/wwwroot/pages/settings/bios.html

Firmware availability page now includes counts of the number available firmware images as well as the total number of known firmware images.
A filter at the top of the page now allows hiding and showing of available and unavailable images.

Enhanced firmware availability page

---

gaseous-server/Classes/Config.cs
gaseous-server/Classes/Logging.cs
gaseous-server/Controllers/V1.0/LogsController.cs
gaseous-server/Controllers/V1.0/SystemController.cs
gaseous-server/Support/Database/MySQL/gaseous-1007.sql
gaseous-server/wwwroot/pages/settings/logs.html
gaseous-server/wwwroot/pages/settings/settings.html
gaseous-server/wwwroot/styles/style.css

* Added filtering options to help find events
* Added an option in Settings to write all logs to disk as well as the database. Default remains to log to the database, with debug and database exceptions logging to disk.

Logs now have filtering options

---

gaseous-server/Classes/Collections.cs
gaseous-server/Classes/Filters.cs
gaseous-server/Classes/Metadata/Storage.cs
gaseous-server/Controllers/V1.1/GamesController.cs
gaseous-server/ProcessQueue.cs
gaseous-server/Support/Database/MySQL/gaseous-1008.sql
gaseous-server/gaseous-server.csproj
gaseous-server/wwwroot/scripts/gamesformating.js
gaseous-server/wwwroot/styles/style.css

* Should resolve performance issues when loading the filter bar content (closes #224):
* by removing unnecessary database calls;
* adding indexes on columns used when running queries;
* more efficient queries selecting _only_ the data required
* Implements early fixes for #223 - more work required to complete that issue, this is a tactical fix to make testing easier

Filter controller performance improvements

---

gaseous-server/Classes/Roms.cs
gaseous-server/Controllers/V1.0/GamesController.cs
gaseous-server/wwwroot/pages/EmulatorJS.html
gaseous-server/wwwroot/pages/dialogs/collectionedit.html
gaseous-server/wwwroot/pages/dialogs/platformmapedit.html
gaseous-server/wwwroot/pages/dialogs/userprofile.html
gaseous-server/wwwroot/pages/emulator.html
gaseous-server/wwwroot/pages/game.html
gaseous-server/wwwroot/pages/home.html
gaseous-server/wwwroot/scripts/filterformating.js
gaseous-server/wwwroot/scripts/gamesformating.js
gaseous-server/wwwroot/scripts/main.js
gaseous-server/wwwroot/styles/style.css

* Removed insta-search and added a search button - closes #203 
* Pagination is constrained to 5 pages on either side of the current page (10 page numbers displayed in total) - closes #223
* Reviewed all dialogs and made behaviour consistent - closes https://github.com/gaseous-project/gaseous-server/issues/225

Improve filter section UX

---

gaseous-server/Classes/FileSignature.cs
gaseous-server/Classes/ImportGames.cs
gaseous-server/Classes/Metadata/Communications.cs
gaseous-server/Classes/Metadata/Games.cs
gaseous-server/Controllers/V1.0/RomsController.cs
gaseous-server/Controllers/V1.0/SearchController.cs
gaseous-server/Models/GaseousGame.cs
gaseous-server/ProcessQueue.cs
gaseous-server/Support/Database/MySQL/gaseous-1012.sql
gaseous-server/Support/Database/MySQL/gaseous-1013.sql
gaseous-server/gaseous-server.csproj
gaseous-server/wwwroot/pages/dialogs/rominfo.html
gaseous-server/wwwroot/scripts/main.js

* Enhanced logging
* Archive contents now stored along with the ROM metadata
* Search results now cached to reduce the number of required IGDB API calls

Multiple Updates

---

gaseous-server/Controllers/V1.1/GamesController.cs
gaseous-server/wwwroot/scripts/filterformating.js
gaseous-server/wwwroot/styles/style.css

Added support for filtering:
* number of rating votes(closes Add filter by number of votes on library page #144)
* release year (closes Add filter by release year #146)

Add filters for number of rating votes, and release year

---

gaseous-server/wwwroot/pages/home.html
gaseous-server/wwwroot/scripts/filterformating.js

Game library should return to the page it was on after a page navigation or refresh

---

README.MD
gaseous-server/Classes/DatabaseMigration.cs
gaseous-server/Support/Database/MySQL/gaseous-1007.sql
gaseous-server/Support/Database/MySQL/gaseous-fix-1005.sql
gaseous-server/gaseous-server.csproj

Minor fixes to complete the upgrade from 1.6.1 to 1.7.0

---

.github/workflows/BuildDockerOnTag-Prerelease.yml
.github/workflows/BuildDockerOnTag-Release.yml
Dockerfile
gaseous-server/Models/PlatformMapping.cs
gaseous-server/Support/PlatformMap.json
gaseous-server/Timer.cs

Integrate EJS 4.0.10

---

gaseous-server/Classes/Config.cs
gaseous-server/Classes/Database.cs

* Fix for broken first run on fresh installs

Fix for broken first run on fresh installs

---

gaseous-server/Classes/Config.cs
gaseous-server/Classes/Database.cs

Error on startup when reading value LastRun_BackgroundDatabaseUpgrade

---

gaseous-server/wwwroot/pages/dialogs/librarynew.html
gaseous-server/wwwroot/pages/settings/settings.html

Closes #303
This fix is a clean up fix - will review functionality for 1.8.0

New library dialog content overruns the edges of the dialog

---

gaseous-server/Classes/Config.cs
gaseous-server/Classes/Database.cs
gaseous-server/Classes/Metadata/Games.cs
gaseous-server/Controllers/V1.1/GamesController.cs
gaseous-server/wwwroot/pages/dialogs/userprofile.html
gaseous-server/wwwroot/scripts/filterformating.js
gaseous-server/wwwroot/scripts/gamesformating.js
gaseous-server/wwwroot/styles/style.css

Closes #316
Overhauled how infinite scrolling works. Should be more reliable now.

Infinite Scrolling breaks clicking the Gaseous Games logo to return to library

---

Dockerfile
gaseous-server/Support/PlatformMap.json

Integrate EJS 4.0.12 - Adds a new Master System core, and a new DS core

---

LICENSE

Change license from GPL to AGPL

---

gaseous-server/Classes/Common.cs

When hashing large files, it can appear that nothing is happening. This change adds log entries before hashes are generated to indicate that hashing is about to begin.

Added extra logging when generating hashes

---

.github/workflows/BuildOnTestBranch.yml
build/entrypoint.sh
build/mariadb.sh
build/supervisord.conf
gaseous-server/wwwroot/pages/settings/about.html

See https://github.com/gaseous-project/unraid-template for an Unraid XML template.

Unraid compatible single container docker image

---

gaseous-server/wwwroot/index.html
gaseous-server/wwwroot/pages/modals/useredit.html
gaseous-server/wwwroot/styles/style.css
gaseous-server/wwwroot/styles/stylevars.css

Resolve some issues with how the new UI renders.

New UI Styling Fixes

---

gaseous-server/Classes/ImportGames.cs
gaseous-server/Models/PlatformMapping.cs

Files will now only be processed if they have extensions defined on the Platform Mapping page.

Ignore and remove files that have unknown extensions

---

gaseous-server/Classes/ImportGames.cs
gaseous-server/Classes/MetadataManagement.cs
gaseous-server/Support/Database/MySQL/gaseous-1025.sql
gaseous-server/wwwroot/pages/first.html
gaseous-server/wwwroot/scripts/account.js
gaseous-server/wwwroot/scripts/cards.js
gaseous-server/wwwroot/scripts/modals.js
gaseous-server/wwwroot/styles/style.css
gaseous-server/wwwroot/styles/stylevars.css

Enhance database performance by updating ROM counts and adding necessary indexes. Improve user interface with new elements and adjustments for better visual presentation.

Database performance enhancements and UI improvements

---

gaseous-server/Classes/CRC32.cs
gaseous-server/Classes/Common.cs
gaseous-server/Classes/FileSignature.cs
gaseous-server/Classes/ImportGames.cs
gaseous-server/Classes/Metadata/Games.cs
gaseous-server/Classes/MetadataManagement.cs
gaseous-server/Classes/SignatureIngestors/XML.cs
gaseous-server/Classes/SignatureManagement.cs
gaseous-server/ProcessQueue.cs
gaseous-server/gaseous-server.csproj
gaseous-server/wwwroot/pages/modals/rominfo.html
gaseous-server/wwwroot/scripts/rominfo.js

DATs can be downloaded from https://github.com/libretro/FBNeo/tree/master/dats

Add FBNeo DAT support

---

gaseous-server/Classes/Metadata/Utility.cs

Implement checks to verify if columns exist before attempting to add them to the database tables, preventing unnecessary errors and ensuring smoother database operations.

Add checks for existing columns before adding to database tables

---

gaseous-server/gaseous-server.csproj

Update the project file to reference the latest versions of several packages for improved functionality and security.

Update package references to latest versions

---

.devcontainer/Dockerfile
build/Dockerfile
build/Dockerfile-EmbeddedDB
gaseous-server/Support/PlatformMap.json
gaseous-server/wwwroot/emulators/EmulatorJS.html
gaseous-server/wwwroot/emulators/EmulatorJS.js
gaseous-server/wwwroot/scripts/cards.js
gaseous-server/wwwroot/scripts/main.js
gaseous-server/wwwroot/styles/style.css

Upgrade the EmulatorJS library to version 4.2.3 and implement new features for improved emulator performance and user experience. This includes updates to the configuration and additional styling for the emulator pause mask.
EJS threading support is also now enabled by default for those cores that have the `requireThreads` attribute set to true.
Added support for newly available EJS platforms such as DOSBOX.

Update EJS to version 4.2.3 and enhance emulator functionality

---

gaseous-server/Classes/Config.cs
gaseous-server/Program.cs

Introduce support for reverse proxy configuration, allowing specification of known proxies and networks. Enhance handling of forwarded headers to utilize this configuration effectively.
- Config file (saved at ~/.gaseous-server/config.json after first run) now includes:
- ReverseProxyConfiguration:
- KnownProxies: ["127.0.0.1", "10.0.0.2"]
- KnownNetworks: ["10.0.0.0/8", "192.168.0.0/16"]
- RequireHeaderSymmetry: false
- Env vars (for use with Docker):
- knownproxies=127.0.0.1,10.0.0.2
- knownnetworks=10.0.0.0/8,192.168.0.0/16
Changes take effect on server restart.

Add reverse proxy configuration support and enhance forwarded headers handling

---

.devcontainer/Dockerfile
gaseous-server/Classes/ImportGames.cs
gaseous-server/Classes/Metadata/Metadata.cs
gaseous-server/Classes/MetadataManagement.cs
gaseous-server/Controllers/V1.0/GamesController.cs
gaseous-server/Controllers/V1.0/SystemController.cs
gaseous-server/Models/MetadataMap.cs
gaseous-server/Support/Database/MySQL/gaseous-1032.sql
gaseous-server/wwwroot/index.html
gaseous-server/wwwroot/scripts/cards.js

Enhance the game import process with better error handling and introduce support for manual configuration and automatic source tracking in metadata management. Update the database schema and frontend handling accordingly.

Support for manually modifying metadata matches
