gaseous-project/gaseous-server

gaseous-server/Controllers/BiosController.cs
gaseous-server/wwwroot/pages/EmulatorJS.html
gaseous-server/wwwroot/pages/emulator.html

Updated EmulatorJS to v4.0.5 and removed option to select BIOS.
BIOS images are now zipped on the fly and presented to the emulator.

feat: updated EmulatorJS to v4.0.5

---

gaseous-server/Classes/ImportGames.cs
gaseous-server/Classes/Metadata/Games.cs
gaseous-server/Classes/MetadataManagement.cs
gaseous-server/Classes/Roms.cs
gaseous-server/Controllers/GamesController.cs
gaseous-server/Program.cs
gaseous-server/gaseous-server.csproj

Pull only that metadata which is required during interactive sessions (during an import for example). The rest of the game metadata will be pull during a metadata refresh, or when the game page is loaded.

Improve metadata first load performance

---

gaseous-server/Classes/ImportGames.cs
gaseous-server/Classes/Metadata/Games.cs
gaseous-server/Classes/MetadataManagement.cs
gaseous-server/Classes/Roms.cs
gaseous-server/Controllers/GamesController.cs
gaseous-server/Program.cs
gaseous-server/gaseous-server.csproj
gaseous-server/wwwroot/pages/game.html
gaseous-server/wwwroot/scripts/main.js
gaseous-server/wwwroot/styles/style.css

Bulk update was hanging when assigning ROMs to a game with no metadata - fetching metadata was taking too long.
Backported a fix that speeds up metadata fetching, and now display a dialog while the process is running.

fix: Update not working after edit

---

gaseous-server/wwwroot/index.html
gaseous-server/wwwroot/pages/home.html
gaseous-server/wwwroot/scripts/filterformating.js
gaseous-server/wwwroot/scripts/main.js

Filter settings on the main page are now stored in a session cookie. This means the settings will be retained until the browser is closed.

Filter settings are now stored in a session cookie

---

gaseous-server/Classes/Bios.cs
gaseous-server/Classes/Collections.cs
gaseous-server/Models/PlatformMapping.cs
gaseous-server/Program.cs
gaseous-server/Support/PlatformMap.json
gaseous-server/wwwroot/pages/dialogs/collectionedit.html
gaseous-server/wwwroot/pages/settings/bios.html
gaseous-tools/Database/MySQL/gaseous-1002.sql

When building Collections, there is now a new drop down to select the folder structure used when compiling a collection:
* Standard: follows the existing behaviour - \IGDB Platform Slug\IGDB Game Slug\ROMs
* Example: \genesis-slash-megadrive\sonic-the-hedgehog\
* RetroPie: follows the folder structure used by the RetroPie project - \roms\Platform Name\ROMs
* Example: \roms\megadrive\
Also added an option to include the BIOS files for any platforms included in the collection (if available) to the collection. These will be deposited in the zip file under /BIOS.

Add support for the RetroPie folder structure when building Collections

---

gaseous-server/Classes/Collections.cs
gaseous-server/Controllers/LogsController.cs
gaseous-server/Program.cs
gaseous-server/wwwroot/pages/settings.html
gaseous-server/wwwroot/pages/settings/logs.html
gaseous-server/wwwroot/scripts/main.js
gaseous-server/wwwroot/styles/style.css
gaseous-tools/Config.cs
gaseous-tools/Logging.cs

* Made logs visible in the UI
* Logs are now always JSON objects appended to a file in ~/.gaseous-server/Logs/ (one JSON object per line)
* Note: this is not a true JSON array, when the server reads the file back for display, it deserialises the log file one line at a time
* Removed references from the configuration file to the "Text" format logs
* Added a retention period for log files (default 30 days) - this option is available in the config file and will appear in existing config files after the next start up

Surface logs in the UI

---

gaseous-server/Classes/ImportGames.cs
gaseous-server/Controllers/RomsController.cs
gaseous-server/wwwroot/pages/dialogs/upload.html

Use the drop down to select the platform you want to use, the selection will apply on the next upload.
Change it back to automatic by selecting "Automatic Platform".
Note that importing via the ~/.gaseous-server/Data/Import does not support platform overrides.

Provide a platform override option during web based import

---

README.MD
gaseous-server/Classes/Metadata/AgeRating.cs
gaseous-server/Classes/Metadata/AgeRatingContentDescriptions.cs
gaseous-server/Classes/Metadata/AlternativeNames.cs
gaseous-server/Classes/Metadata/Artworks.cs
gaseous-server/Classes/Metadata/Collections.cs
gaseous-server/Classes/Metadata/Company.cs
gaseous-server/Classes/Metadata/CompanyLogos.cs
gaseous-server/Classes/Metadata/Covers.cs
gaseous-server/Classes/Metadata/ExternalGames.cs
gaseous-server/Classes/Metadata/Franchises.cs
gaseous-server/Classes/Metadata/GameModes.cs
gaseous-server/Classes/Metadata/GameVideos.cs
gaseous-server/Classes/Metadata/Games.cs
gaseous-server/Classes/Metadata/Genres.cs
gaseous-server/Classes/Metadata/InvolvedCompany.cs
gaseous-server/Classes/Metadata/MultiplayerModes.cs
gaseous-server/Classes/Metadata/PlatformLogos.cs
gaseous-server/Classes/Metadata/PlatformVersions.cs
gaseous-server/Classes/Metadata/Platforms.cs
gaseous-server/Classes/Metadata/PlayerPerspectives.cs
gaseous-server/Classes/Metadata/Screenshots.cs
gaseous-server/Classes/Metadata/Themes.cs

If an error occurs when updating metadata from IGDB, the exception is now logged and any cached value is returned.

Fail safe when the IGDB connector experiences an exception

---

gaseous-server/Classes/ImportGames.cs
gaseous-server/Models/PlatformMapping.cs
gaseous-server/ProcessQueue.cs
gaseous-server/Program.cs
gaseous-server/Support/PlatformMap.json
gaseous-tools/Database/MySQL/gaseous-1004.sql

Removed the rematching task from LibraryScan - this process now only has one job: to ensure the database is consistent with what's on disk.
Created a new task called Rematcher - it runs once a day (every 1440 minutes), and only on a limited subset of targets. It selects the first 100 ROM's which have a platform or a game of unknown, AND who's last rematch date was more than 30 days ago (or NULL).

Split LibraryScan and Rematching into separate background tasks

---

gaseous-server/Classes/Maintenance.cs
gaseous-server/ProcessQueue.cs
gaseous-server/Program.cs
gaseous-server/wwwroot/styles/style.css

Maintenance task now runs once a week. It blocks all other tasks.
It deletes files in the Temp and Upload directories that are older than 30 days, and it runs a database optimisation.
Both the Temp and Upload directories are deleted on start up.

Added cleanup and database optimisation

---

gaseous-server/Support/PlatformMap.json

Adds cores to PlatformMap.json for platforms (closes #315):
* Family Computer = fceumm
* Super Famicom = snes9x
* TurboGrafx-16/PC Engine + Turbografx-16/PC Engine CD = mednafen_pce
* Neo Geo Pocket + Neo Geo Pocket Color = mednafen_ngp
* Wonderswan + Wonderswan Color = mednafen_wswan
* Nec PC-FX = mednafen_pcfx

Update for PlatformMap.json to add missing core support

---

gaseous-server/wwwroot/emulators/EmulatorJS.html
gaseous-server/wwwroot/pages/emulator.html

Closes #317
Removes the save and load file buttons - leaving the save and load state buttons

Hide unneeded buttons from the emulator

---

gaseous-server/Controllers/V1.0/SearchController.cs
gaseous-server/wwwroot/pages/dialogs/rominfo.html

Issue was due to the search result limit being too low. Increased the search result size to 100 returned objects.

When fixing matches, search doesn't return the correct values

---

gaseous-server/Classes/Roms.cs
gaseous-server/Controllers/V1.1/StateManagerController.cs
gaseous-server/wwwroot/pages/dialogs/emulatorloadstate.html
gaseous-server/wwwroot/pages/emulator.html

This change provides the ability to upload save states.
When a state is downloaded, the state (savestate.state), screenshot (screenshot.jpg), and a json file (rominfo.json) describing the save state are zipped and downloaded.
The json file description is defined as follows:
```json
{
"Name": "Super Mario Bros. (1985-09-13)(Nintendo)(JP-US).zip",
"StateDateTime": "2024-06-24T05:34:38",
"StateName": "",
"MD5": "7d158dcd242e77ba249ac8342474aa77",
"SHA1": "3d4b04dc78f9d998f17d9fe9ad982a83b5ed72df",
"Type": "ROM"
}
```
| Attribute | Value |
| -------- | ------|
| Name | The name of the ROM that the state belongs to. This is merely a convenience attribute. |
| StateDateTime | The date and time (in UTC) when the state was initially saved. |
| StateName | The name of the state |
| MD5 | The MD5 …

Provide ability to upload save states

---

.github/workflows/BuildDockerOnTag-Prerelease.yml
.github/workflows/BuildDockerOnTag-Release.yml

This PR modifies the build process to generate two docker images; the standard image, and one with MariaDB embedded into it for one click installs.
This embedded MariaDB image is meant to support users on systems like Unraid that don't easily support docker-compose.
Also; for users on Unraid, it will allow the creation of a single click install template to be submitted to the Unraid marketplace (this will be done at a later date after the release of 1.7.4).

Build a docker image that includes an embedded MariaDB server

---

gaseous-server/Classes/Metadata/Covers.cs
gaseous-server/Classes/Metadata/Games.cs
gaseous-server/Classes/Metadata/Storage.cs
gaseous-server/Controllers/V1.0/SearchController.cs
gaseous-server/Models/GaseousGame.cs
gaseous-server/Program.cs
gaseous-server/wwwroot/scripts/main.js
gaseous-server/wwwroot/styles/style.css

* Resolved missing table errors.
* These were due to some dynamically created tables being queried before they were created.
* These tables are now created at start up.
* Resolved many "INSERT" errors that were polluting the logs:
* These were due to a race condition where sometimes the database would return the data as not being in the database causing Gaseous to try to insert it - even though the data was already there.

Resolved many database errors

---

gaseous-server/Classes/Maintenance.cs

During the daily maintenance task, server logs are now deleted in 1000 record chunks. It repeats this a maximum of 1000 times or until there are no more records left to delete.
During the weekly maintenance task, the optimise task now has a longer timeout.
Closes #352

Improved maintenance tasks

---

gaseous-server/Support/Database/MySQL/gaseous-1022.sql
gaseous-server/gaseous-server.csproj

IGDB has recently added a new platform who's name exceeds 45 characters (the maximum Name length in the Platform table). This change extends the character length to 255 chars.

Expand the platform table name field to accomodate larger platform names

---

build/embeddeddb/entrypoint.sh
build/standard/entrypoint.sh
gaseous-server/Classes/Config.cs
gaseous-server/Classes/DatabaseMigration.cs
gaseous-server/Classes/Filters.cs
gaseous-server/Classes/GameLibrary.cs
gaseous-server/Classes/ImportGames.cs
gaseous-server/Classes/Metadata/Games.cs
gaseous-server/Classes/Roms.cs
gaseous-server/Controllers/V1.0/GamesController.cs
gaseous-server/Controllers/V1.0/PlatformsController.cs
gaseous-server/Controllers/V1.0/SystemController.cs
gaseous-server/Controllers/V1.1/GamesController.cs
gaseous-server/Program.cs
gaseous-server/Support/Database/MySQL/gaseous-1024.sql

The migration of the docker container to a rootless one requires the default library to move.
This change strips the library path from the path to the ROM and replaces it with an SQL view that concatenates the library path and ROM path.

Fix for home path change

---

gaseous-server/Classes/Bios.cs
gaseous-server/Classes/Config.cs
gaseous-server/Classes/ImportGames.cs
gaseous-server/Controllers/V1.0/BiosController.cs
gaseous-server/Program.cs

Many of the platforms are similar enough to other platforms that they'll share the same BIOS files.
The current storage method stores BIOS files per platform, meaning that files can be duplicated multiple times to satisfy the requirements of each platform.
This change stores the files as their hash with a .bios extension (example: `85ad74194e87c08904327de1a9443b7a.bios`) in a flat directory structure. This allows BIOS files that are used by multiple platforms to be shared without duplication.

Revamp of BIOS handling

---

build/Dockerfile
gaseous-server/Controllers/V1.1/HealthCheckController.cs

The purpose of this endpoint is to respond only with http code 200, to be used by services such as Docker to check if the server is still running.

Add a healthcheck endpoint

---

build/Dockerfile
build/Dockerfile-EmbeddedDB
gaseous-server/Program.cs
gaseous-server/Support/PlatformMap.json
gaseous-server/wwwroot/emulators/EmulatorJS.html

- Upgraded EmulatorJS to the latest version - see https://github.com/EmulatorJS/EmulatorJS/releases/tag/v4.2.1 for more details
- Added support for browser emulation of Playstation Portable via EmulatorJS - note, this does not work under the Safari browser

Upgrade EmulatorJS version to 4.2.1

---

gaseous-server/Classes/DatabaseMigration.cs
gaseous-server/Classes/SignatureIngestors/XML.cs
gaseous-server/Program.cs
gaseous-server/Support/Database/MySQL/gaseous-1024.sql
gaseous-server/gaseous-server.csproj

Resolves bugs when importing signature DATs.
For existing installs, the database upgrade will trigger a full re-import of all DATs on startup to correct gaps or errors in the database. This process may take some time.

Resolves bugs when importing Signatures

---

gaseous-server/Classes/SignatureManagement.cs

Fixed an issue with reading ROM DAT attributes that was causing an error for some users blocking ROMs from being loaded properly.
If the attributes fail to load, an error will be logged with some details about the broken data, and continue without issue.

Fixed issue with reading ROM DAT attributes

---

gaseous-server/wwwroot/scripts/modals.js

Potential fix for [https://github.com/gaseous-project/gaseous-server/security/code-scanning/32](https://github.com/gaseous-project/gaseous-server/security/code-scanning/32)
To fix the issue, the value of `data-tabname` should be treated as plain text and not as HTML. Instead of assigning it to `innerHTML`, which interprets the value as HTML, it should be assigned to `textContent`, which safely sets the text content of the element without interpreting it as HTML. This ensures that any special characters in the `data-tabname` value are escaped and displayed as-is, preventing potential XSS attacks.
The changes should be made on line 65 and line 44, where `innerHTML` is used to set the content of DOM elements based on `data-tabname`.
---
_Suggested fixes powered by Copilot Autofix. Review …

Potential fix for code scanning alert no. 32: DOM text reinterpreted as HTML

---

installer/setup/Setup.wixproj

Upgrade the WiX Toolset SDK version in the project configuration to ensure compatibility with the latest features and improvements.

Update WiX Toolset SDK to version 6.0.2

---

gaseous-server/Support/PlatformMap.json

The current GBA core is loading the `gb` core instead of the `gba`, preventing GBA games from running.
(Screenshot from a GBA game)
This is a simple fix to address this issue.

Fix GBA core value
